version: '3.8'

services:
  sharding-storage:
    image: l1zail/sharding-storage:latest
    build: .
    container_name: sharding-storage
    ports:
      - "8090:8080"
    restart: unless-stopped
    networks:
      - sharding-network

  master-node:
    image: l1zail/master-node:latest
    container_name: master-node
    ports:
      - "9090:8080"
    restart: unless-stopped
    networks:
      - sharding-network

  sharding-client:
    image: l1zail/sharding-client:latest
    container_name: sharding-client
    ports:
      - "7070:8080"
    command: ["master-node:9090"]
    restart: on-failure
    stdin_open: true
    tty: true
    networks:
      - sharding-network

networks:
  sharding-network:
    driver: bridge