name: runner

on:
  push:
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'gradle'

      - name: Grant execute permissions to Gradle wrapper
        run: chmod +x gradlew

      - name: Run Tests
        run: ./gradlew test --warning-mode all

      - name: Publish Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test
          
  docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version info
        id: version
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "TAG=$SHORT_SHA" >> $GITHUB_ENV
          echo "tag=$SHORT_SHA" >> $GITHUB_OUTPUT

      - name: Build and Push Multi-Platform Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            l1zail/sharding-storage:${{ env.TAG }}
            l1zail/sharding-storage:latest